/* blog.js - client-side post index loader.
 * Reads /blog/posts.json (generated by build.ps1) and replaces the bundled
 * fallback list on /blog/ with the latest metadata.
 */
(function () {
    'use strict';

    var list = document.getElementById('blog-list');
    if (!list) return;

    function escapeHtml(s) {
        return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
            return ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[c];
        });
    }

    function renderTags(tags) {
        return (tags || []).map(function (tag) {
            return '<span class="tag">' + escapeHtml(tag) + '</span>';
        }).join('');
    }

    function renderPost(post) {
        var minutes = Number(post.readingTime || 1);
        var read = minutes === 1 ? '1 min read' : (minutes + ' min read');
        return '<li class="card">' +
            '<h3><a href="' + escapeHtml(post.url) + '">' + escapeHtml(post.title) + '</a></h3>' +
            '<div class="meta">' + escapeHtml(post.date) + ' &middot; ' + escapeHtml(read) + '</div>' +
            '<p class="summary">' + escapeHtml(post.summary) + '</p>' +
            renderTags(post.tags) +
            '</li>';
    }

    fetch('/blog/posts.json', { cache: 'no-store' })
        .then(function (r) {
            if (!r.ok) throw new Error('HTTP ' + r.status);
            return r.json();
        })
        .then(function (payload) {
            if (!payload || !Array.isArray(payload.posts) || payload.posts.length === 0) return;
            list.innerHTML = payload.posts.map(renderPost).join('');
        })
        .catch(function () {
            var note = document.createElement('p');
            note.className = 'text-muted fs-sm';
            note.textContent = 'Could not refresh the generated post index. Showing bundled entries instead.';
            list.insertAdjacentElement('afterend', note);
        });
})();
